# Generated by Django 4.1.5 on 2023-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_name_alter_street_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
