# Generated by Django 4.1.5 on 2023-02-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_alter_street_name_street_name_city_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='city.city', to_field='name'),
        ),
    ]
