# Generated by Django 4.1.5 on 2023-02-02 05:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_alter_street_city'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AddField(
            model_name='shop',
            name='house',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.street'),
        ),
        migrations.AddField(
            model_name='shop',
            name='to_close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='to_open_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
