# Generated by Django 4.1.5 on 2023-02-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_city_shop_house_shop_street_shop_to_close_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='street',
        ),
    ]
