# Generated by Django 4.1.5 on 2023-02-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_alter_street_city'),
        ('shop', '0003_remove_shop_city_remove_shop_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
    ]
